language: ruby
rvm:
  - 2.4.0

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

before_install:
  - gem install bundler

script:
  - RAILS_ENV=test bundle exec rake spec && bundle exec codeclimate-test-reporter

cache: bundler
sudo: false
